
package cxf.com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Mon Aug 19 22:53:25 IST 2019
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "readMarks", namespace = "http://com.cxf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "readMarks", namespace = "http://com.cxf/")

public class ReadMarks {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

